"""empty message

Revision ID: 7ce3003a71a3
Revises: 
Create Date: 2022-12-30 13:49:59.733483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce3003a71a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['reviewer'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewer')

    # ### end Alembic commands ###
